# fly.toml app configuration file generated for validacao on 2024-09-28T16:01:39-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "validacao"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
